try:
    raise ValueError()
except Exception as e:
    pass

print("here")
